site_name: The Neurostuff Ecosystem
site_url: https://neurostuff.github.io/
theme:
    name: material
    favicon: images/favicon.png
    logo: images/logo.png
markdown_extensions:
    - toc:
        anchorlink: true
    - admonition
docs_dir: 'docs'
nav:
    - The Neurostuff Ecosytem: index.md
